### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by KingOfPower2828** [ESX-Org/esx_drugs#16] opened 2017-10-10 19:10 UTC
There is a bug where you can manipulate the drug interaction zones to add, process & sell more than one at a time its basically where u go in and out of the zone pressing e and it will make the drug circle do the event more than once at a time

**Comment by ElPumpo** [comment] 2018-04-05 09:25
Duplicate of #18, closing

**Closed by ElPumpo** 2018-04-05 09:25 UTC
